version: "3.7"

services:
  mysql:
    image: mysql/mysql-server:8.0.31
    ports:
      - 33307:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: nimda

volumes:
  mysql-data: